Pandas on excel.

In [5]:
import pandas as pd
df=pd.read_excel("Movies_data_2000.xlsx")
df.head()

,Title,Budget,ID,Original Language,Popularity,Release Date,Revenue,Runtime,Vote Average,Vote Count
0,Baywatch,69000000,339846,en,35.637691,2017-12-05,177856751,116.0,6.1,1829
1,The Wall,0,405775,en,15.597500,2017-12-05,1803009,89.0,6.1,117
2,Gifted,7000000,400928,en,16.025911,2017-12-04,37461045,101.0,7.7,549
3,The Spacewalker,7075038,440642,ru,10.181000,2017-12-04,9868942,140.0,7.4,20
4,The Fate of the Furious,250000000,337339,en,48.573287,2017-12-04,1238764765,136.0,6.8,3803

In [8]:
df["Budget"]

0        69000000
1               0
2         7000000
3         7075038
4       250000000
          ...
4530     25000000
4531     10000000
4532    103000000
4533      6000000
4534      1000000
Name: Budget, Length: 4535, dtype: int64

In [12]:
df[df["Vote Average"] > 8]

,Title,Budget,ID,Original Language,Popularity,Release Date,Revenue,Runtime,Vote Average,Vote Count
115,In This Corner of the World,0,378108,ja,2.914029,2016-12-11,19204593,128.0,8.7,19
190,A Silent Voice,0,378064,ja,34.852055,2016-09-17,19606617,130.0,8.1,157
205,Your Name.,0,372058,ja,34.461252,2016-08-26,355298270,106.0,8.5,1030
390,The Handmaiden,8575000,290098,ko,16.727405,2016-01-06,1983204,145.0,8.1,453
417,Katyar Kaljat Ghusali,1500000,368330,mr,0.446454,2015-12-11,4400000,162.0,9.0,2
468,Room,6000000,264644,en,12.443291,2015-10-16,35401758,117.0,8.1,2838
524,The Beauty Inside,0,338729,ko,2.978534,2015-08-20,108083,127.0,8.1,41
725,The Guide,722083,293122,en,0.817488,2014-12-11,499168,120.0,8.6,6
775,Whiplash,3300000,244786,en,64.299990,2014-10-10,13092000,105.0,8.3,4376
791,The Salt of the Earth,0,265297,fr,5.154091,2014-09-27,1059804,109.0,8.1,146
887,Song of the Sea,0,110416,en,6.967358,2014-06-09,857522,93.0,8.1,420
908,Mommy,4900000,265177,en,14.876086,2014-05-22,3494070,138.0,8.2,734
925,Interstellar,165000000,157336,en,32.213481,2014-05-11,675120017,169.0,8.1,11187
1041,Drishyam,750000,244049,ml,1.908761,2013-12-19,12000000,160.0,8.1,23
1696,My Grandfather's People,0,81708,en,1.391176,2011-11-25,6086224,123.0,8.1,7
1743,Louis C.K.: Live at the Beacon Theater,250000,80379,en,4.297654,2011-10-12,1000000,62.0,8.1,80
1928,The Last Mountain,0,53328,en,0.078210,2011-03-06,90425,95.0,9.0,2
1944,The Intouchables,13000000,77338,fr,16.086919,2011-02-11,426480871,112.0,8.2,5410
2129,Inception,160000000,27205,en,29.108149,2010-07-14,825532764,148.0,8.1,14075
2132,Senna,0,58496,en,11.331859,2010-07-10,8212430,106.0,8.1,282
2709,The Dark Knight,185000000,155,en,123.167259,2008-07-16,1004558444,152.0,8.3,12269
3192,Lake of Fire,0,44260,en,0.915050,2006-09-09,25,152.0,8.1,11
3634,Howl's Moving Castle,24000000,4935,ja,16.136048,2004-11-19,234710455,119.0,8.2,2049
3843,The Visual Bible: The Gospel of John,10000000,30973,en,1.551648,2003-11-09,4069090,125.0,8.2,12
3992,The Lord of the Rings: The Return of the King,94000000,122,en,29.324358,2003-01-12,1118888979,201.0,8.1,8226
4025,Cuban Rafters,0,27915,es,0.525869,2002-12-04,62153,120.0,9.0,2
4063,The Pianist,35000000,423,en,14.811594,2002-09-24,120072577,150.0,8.1,1927
4089,Desmundo,3,161244,pt,0.265070,2002-08-11,3,101.0,9.0,1
4131,Washington Heights,0,251053,en,0.601936,2002-05-22,156021,89.0,8.5,3
4140,City of God,3300000,598,pt,14.959270,2002-05-02,30641770,130.0,8.2,1852
4283,Spirited Away,15000000,129,ja,41.048867,2001-07-20,274925095,125.0,8.3,3968
4404,Memento,9000000,77,en,15.450789,2000-11-10,39723096,113.0,8.1,4168

In [14]:
print(df.to_string())

                                                                                    Title     Budget      ID Original Language  Popularity Release Date     Revenue  Runtime  Vote Average  Vote Count
0                                                                                Baywatch   69000000  339846                en   35.637691   2017-12-05   177856751    116.0           6.1        1829
1                                                                                The Wall          0  405775                en   15.597500   2017-12-05     1803009     89.0           6.1         117
2                                                                                  Gifted    7000000  400928                en   16.025911   2017-12-04    37461045    101.0           7.7         549
3                                                                         The Spacewalker    7075038  440642                ru   10.181000   2017-12-04     9868942    140.0           7.4          20
4                                                                 The Fate of the Furious  250000000  337339                en   48.573287   2017-12-04  1238764765    136.0           6.8        3803
5                                                                               Sleepless   30000000  324542                en   12.240817   2017-12-01    32540674     95.0           5.8         345
6                                                                         The Bye Bye Man    7400000  292280                en   19.225832   2017-12-01    26667197     96.0           5.1         262
7                                                                                Bairavaa          0  411717                ta    1.459459   2017-12-01    17000000    168.0           6.5          12
8                                                                               Good Time          0  429200                en    5.798555   2017-11-08    10893246     99.0           7.3          46
9                                                          War for the Planet of the Apes  152000000  281338                en  146.161786   2017-11-07   369907963    140.0           6.7        1675
10                                                                       The Glass Castle          0  336000                en    7.892689   2017-10-08     9705840    127.0           6.5          29
11                                                                 The Ottoman Lieutenant   40000000  433356                en   13.256679   2017-10-03      240978    111.0           6.5          38
12                                                                      Rescue Under Fire          0  437031                es   33.536359   2017-10-03     5000000     93.0           6.1          17
13                                                                               The Hero          0  425751                en    6.549788   2017-09-06     3384747     97.0           6.7          17
14                                                                        Alien: Covenant   97000000  126889                en   72.884078   2017-09-05   232380243    122.0           5.7        2677
15                                                                         A Few Less Men          0  413391                en    1.475321   2017-09-03      123899     96.0           5.2          11
16                                                                       My Cousin Rachel          0  413998                en   12.855228   2017-08-06     2676077    106.0           5.7          91
17                                                                     Kong: Skull Island  185000000  293167                en   29.429112   2017-08-03   566652812    118.0           6.2        3161
18                                                                  The Lego Batman Movie   80000000  324849                en   17.070748   2017-08-02   311950384    104.0           7.2        1473
19                                                                   John Wick: Chapter 2   40000000  324552                en   49.247505   2017-08-02   171539887    122.0           6.7        2924
20                                                                    Fifty Shades Darker   55000000  341174                en   29.130443   2017-08-02   378827494    118.0           6.0        2341
21                                                                        The Emoji Movie   50000000  378236                en   33.694599   2017-07-28    66913939     86.0           5.8         327
22                                                                          Atomic Blonde   30000000  341013                en   14.455104   2017-07-26    90007945    115.0           6.1         748
23                                            Valerian and the City of a Thousand Planets  197471676  339964                en   15.262706   2017-07-20    90024292    137.0           6.7         905
24                                                                                Dunkirk  100000000  374720                en   30.938854   2017-07-19   519876949    107.0           7.5        2712
25                                                                          A Ghost Story     100000  428449                en   24.339781   2017-07-07    15584255     92.0           6.8          95
26                                                                               02:22:00          0  269795                en   37.484577   2017-06-29         422     99.0           5.5         277
27                                                                            Baby Driver   34000000  339403                en  228.032744   2017-06-28   224511319    113.0           7.2        2083
28                                                                           The Big Sick          0  416477                en   23.424794   2017-06-23    52620184    120.0           7.7         249
29                                                                           The Beguiled   10500000  399019                en   36.260510   2017-06-23    25442939     93.0           5.8         279
30                                                          Transformers: The Last Knight  260000000  335988                en   39.186819   2017-06-21   604942143    149.0           6.2        1440
31                                                                      The Book of Henry   10000000  382614                en   24.553725   2017-06-16     4219536    105.0           7.6          84
32                                                                         47 Meters Down    5500000  403119                en   52.854103   2017-06-15    44235023     89.0           5.1         548
33                                                                                 Cars 3  175000000  260514                en   19.148182   2017-06-15   350170057    109.0           6.6         718
34                                                                            Rough Night   20000000  397422                en   24.317924   2017-06-15    45056771    101.0           5.6         336
35                                                                        Despicable Me 3   80000000  324852                en   36.631519   2017-06-15  1020063384     96.0           6.2        2002
36                                                                              The Mummy  125000000  282035                en   33.704935   2017-06-06   407778013    110.0           5.4        2122
37                                                                               Colossal          0  339967                en   25.373662   2017-06-04     3021345    110.0           6.2         394
38                                                                           Their Finest   32745300  340101                en   17.958512   2017-06-04    12173470    117.0           7.1          64
39                                                                         Going in Style   25000000  353070                en   15.157255   2017-06-04    84618541     96.0           6.6         543
40                                                                              Aftermath   10500000  390051                en   10.150041   2017-06-04        3451     92.0           5.8         162
41                                                                           Wonder Woman  149000000  297762                en  294.337037   2017-05-30   820580447    141.0           7.2        5025
42                                                                        Berlin Syndrome          0  363126                en   12.211769   2017-05-25      201719    116.0           6.0         100
43                                       Pirates of the Caribbean: Dead Men Tell No Tales  230000000  166426                en  133.827820   2017-05-23   794191988    129.0           6.6        2814
44                                                    Diary of a Wimpy Kid: The Long Haul   22000000  417830                en   28.176992   2017-05-19    40120144     91.0           6.1          48
45                                                                             The Dinner          0  401546                en    5.175311   2017-05-05     1323312    120.0           4.1          44
46                                                                             The Lovers          0  426253                en    2.968282   2017-05-05      214078     94.0           5.4           8
47                                                                     Buster's Mal Heart          0  367147                en    2.796081   2017-04-28       73121     96.0           6.1          41
48                                                                              Lowriders     916000  333384                en    4.612622   2017-04-28     2403885     99.0           7.0          20
49                                                                How to Be a Latin Lover          0  425134                en    7.299803   2017-04-28    26251899    115.0           6.1          85
50                                                                             The Circle   18000000  339988                en   88.439243   2017-04-27    20497844    110.0           5.4        1015
51                                                       King Arthur: Legend of the Sword  175000000  274857                en   44.251369   2017-04-27   146175066    126.0           6.5        1506
52                                                            Baahubali 2: The Conclusion   18000000  350312                te    9.042261   2017-04-27   230000000    161.0           6.7         161
53                                                                      Phoenix Forgotten    2800000  443319                en   12.560942   2017-04-21     3600000     80.0           5.7          52
54                                                                          Unforgettable   12000000  418437                en   10.159713   2017-04-20    17768012    100.0           5.7         117
55                                                         Guardians of the Galaxy Vol. 2  200000000  283995                en  185.330992   2017-04-19   863416141    137.0           7.6        4858
56                                                                    Spark: A Space Tail          0  322487                en   10.348612   2017-04-14      116873     97.0           4.8          10
57                                                                          Chasing Trane          0  411012                en    0.519968   2017-04-14      393970     99.0           8.0           2
58                                                                                 Kidnap   21000000  293768                en   20.214579   2017-04-08    24527158     95.0           6.0         244
59                                                                              Free Fire   10000000  334521                en   10.403003   2017-03-31     3565109     90.0           6.3         232
60                                                                   The Zookeeper's Wife   20000000  289222                en   13.655178   2017-03-31    13162475    126.0           7.1         160
61                                                                     Ghost in the Shell  110000000  315837                en   68.726676   2017-03-29   169801921    107.0           5.9        2547
62                                                                                 Wilson          0  346681                en    8.984386   2017-03-24      653951     94.0           6.1          81
63                                                                          The Boss Baby  125000000  295693                en   13.392824   2017-03-23   498814908     97.0           6.1        2336
64                                                                          Power Rangers  100000000  305470                en   23.247298   2017-03-23   142337240    124.0           6.3        1321
65                                                                                  CHiPS   25000000  417644                en   12.238061   2017-03-23    26800152    100.0           6.2         277
66                                                               Smurfs: The Lost Village   60000000  137116                en   16.972835   2017-03-23   197183546     89.0           6.2         311
67                                                                                   Life   58000000  395992                en   36.263803   2017-03-22   100541806    103.0           6.3        1959
68                                                                           Song to Song   10000000  330947                en   12.928712   2017-03-17      443684    129.0           5.4         179
69                                                                   Beauty and the Beast  160000000  321612                en  287.253654   2017-03-16  1262886337    129.0           6.8        5530
70                                                                         The Dark Tower   60000000  353491                en   50.903593   2017-03-08    71000000     95.0           5.7         688
71                                                                             Wind River   11000000  395834                en   40.796775   2017-03-08   184770205    111.0           7.4         181
72                                                                               Snatched   42000000  373569                en   11.214779   2017-03-05    60845711     90.0           5.2         207
73                                                                              The Shack   20000000  345938                en   16.392712   2017-03-03    57330873    132.0           6.9         330
74                                                                          The Last Word          0  396810                en    7.248414   2017-03-03     1783421    108.0           6.5          59
75                                                                               Ok Jaanu          0  413882                hi    4.448075   2017-03-01      345872    135.0           6.0          20
76                                                                                  Logan   97000000  263115                en   54.581997   2017-02-28   616801808    137.0           7.6        6310
77                                                                                Get Out    5000000  419430                en   36.894806   2017-02-24   252434250    104.0           7.2        2978
78                                                               The Man Who Was Too Free          0  437372                ru    0.176653   2017-02-23       77156    126.0           0.0           0
79                                                                         Bitter Harvest   20000000  403390                en    3.573865   2017-02-23      557241    103.0           6.7          22
80                                                                                     XX          0  297160                en    8.106953   2017-02-17       30911     80.0           5.0         106
81                                                                               Lovesong          0  371447                en    2.605017   2017-02-17        6700     85.0           6.4          30
82                                                                       Have Fun, Vasya!     707503  430263                ru    1.681316   2017-02-16     4781454     90.0           7.2          13
83                                                                    A Cure for Wellness   40000000  340837                en   13.284360   2017-02-15    26559557    146.0           6.0         939
84                                                                              Alibi.com          0  398929                fr    9.095460   2017-02-15      222430     90.0           6.9         389
85                                                                          Before I Fall    5000000  397837                en   38.995136   2017-02-03    10025571     98.0           6.8         651
86                                                                           Kung Fu Yoga   65000000  383785                zh   17.630487   2017-01-27   254212245    130.0           5.9          50
87                                                                       T2 Trainspotting   18000000  180863                en   17.645877   2017-01-27    41412709    117.0           7.1         795
88                                                                   The Space Between Us   30000000  365942                en   11.824404   2017-01-26    14793385    121.0           7.2         564
89                                                                           Lady Macbeth          0  410117                en    9.732026   2017-01-20         923     89.0           6.7          89
90                                                                               Table 19    5000000  353569                en    8.645067   2017-01-20     3305592     87.0           6.2         192
91                                                                        A Dog's Purpose   22000000  381289                en    9.863789   2017-01-19   194647323    100.0           6.6         657
92                                                                             Black Snow    4000000  425942                es   10.067238   2017-01-19     1440000     90.0           6.0          39
93                                                                Confidential Assignment    8520000  434119                ko    1.758590   2017-01-18    56100000    125.0           6.2           5
94                                                             xXx: Return of Xander Cage   85000000   47971                en   17.918269   2017-01-13   346147658    107.0           5.5        1497
95                                               Captain Underpants: The First Epic Movie   38000000  268531                en   88.561239   2017-01-06   110824373     89.0           6.5         159
96                                                                                  Rings   25000000   14564                en   24.535733   2017-01-02    83080890    102.0           4.8        1075
97                                                                                 Sahara          0  423453                fr    8.665106   2017-01-02     7800000     86.0           5.4          43
98                                                                          Live by Night  108000000  259695                en   19.943930   2016-12-25    22678555    129.0           6.2         416

In [17]:
df["Budget"].sum()

np.int64(129970141357)

In [18]:
df["Budget"].count()

np.int64(4535)

In [19]:
df.isnull().sum()

Title                0
Budget               0
ID                   0
Original Language    0
Popularity           0
Release Date         0
Revenue              0
Runtime              3
Vote Average         0
Vote Count           0
dtype: int64

In [20]:
df.dropna()

,Title,Budget,ID,Original Language,Popularity,Release Date,Revenue,Runtime,Vote Average,Vote Count
0,Baywatch,69000000,339846,en,35.637691,2017-12-05,177856751,116.0,6.1,1829
1,The Wall,0,405775,en,15.597500,2017-12-05,1803009,89.0,6.1,117
2,Gifted,7000000,400928,en,16.025911,2017-12-04,37461045,101.0,7.7,549
3,The Spacewalker,7075038,440642,ru,10.181000,2017-12-04,9868942,140.0,7.4,20
4,The Fate of the Furious,250000000,337339,en,48.573287,2017-12-04,1238764765,136.0,6.8,3803
...,...,...,...,...,...,...,...,...,...,...
4530,Highlander: Endgame,25000000,12211,en,11.430964,2000-01-09,15843608,87.0,4.4,107
4531,Snatch,10000000,107,en,14.014025,2000-01-09,83557872,103.0,7.7,2953
4532,Gladiator,103000000,98,en,23.186667,2000-01-05,457640427,155.0,7.9,5566
4533,3 Strikes,6000000,47816,en,0.651625,2000-01-03,9000000,82.0,5.9,15
4534,The Broken Hearts Club: A Romantic Comedy,1000000,22597,en,1.795849,2000-01-02,1744858,94.0,6.3,26

In [21]:
df.isnull().sum()

Title                0
Budget               0
ID                   0
Original Language    0
Popularity           0
Release Date         0
Revenue              0
Runtime              3
Vote Average         0
Vote Count           0
dtype: int64

In [22]:
df.fillna(0)

,Title,Budget,ID,Original Language,Popularity,Release Date,Revenue,Runtime,Vote Average,Vote Count
0,Baywatch,69000000,339846,en,35.637691,2017-12-05,177856751,116.0,6.1,1829
1,The Wall,0,405775,en,15.597500,2017-12-05,1803009,89.0,6.1,117
2,Gifted,7000000,400928,en,16.025911,2017-12-04,37461045,101.0,7.7,549
3,The Spacewalker,7075038,440642,ru,10.181000,2017-12-04,9868942,140.0,7.4,20
4,The Fate of the Furious,250000000,337339,en,48.573287,2017-12-04,1238764765,136.0,6.8,3803
...,...,...,...,...,...,...,...,...,...,...
4530,Highlander: Endgame,25000000,12211,en,11.430964,2000-01-09,15843608,87.0,4.4,107
4531,Snatch,10000000,107,en,14.014025,2000-01-09,83557872,103.0,7.7,2953
4532,Gladiator,103000000,98,en,23.186667,2000-01-05,457640427,155.0,7.9,5566
4533,3 Strikes,6000000,47816,en,0.651625,2000-01-03,9000000,82.0,5.9,15
4534,The Broken Hearts Club: A Romantic Comedy,1000000,22597,en,1.795849,2000-01-02,1744858,94.0,6.3,26

In [23]:
df.isnull().sum()

Title                0
Budget               0
ID                   0
Original Language    0
Popularity           0
Release Date         0
Revenue              0
Runtime              3
Vote Average         0
Vote Count           0
dtype: int64

In [24]:
df.isnull()

,Title,Budget,ID,Original Language,Popularity,Release Date,Revenue,Runtime,Vote Average,Vote Count
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
4530,False,False,False,False,False,False,False,False,False,False
4531,False,False,False,False,False,False,False,False,False,False
4532,False,False,False,False,False,False,False,False,False,False
4533,False,False,False,False,False,False,False,False,False,False
4534,False,False,False,False,False,False,False,False,False,False

In [25]:
df.isnull().any()

Title                False
Budget               False
ID                   False
Original Language    False
Popularity           False
Release Date         False
Revenue              False
Runtime               True
Vote Average         False
Vote Count           False
dtype: bool

In [26]:
df["Runtime"] = df["Runtime"].fillna(df["Runtime"].mean())

In [27]:
df.isnull().sum()

Title                0
Budget               0
ID                   0
Original Language    0
Popularity           0
Release Date         0
Revenue              0
Runtime              0
Vote Average         0
Vote Count           0
dtype: int64

In [32]:
df.sort_values(by="Runtime", ascending=True)

,Title,Budget,ID,Original Language,Popularity,Release Date,Revenue,Runtime,Vote Average,Vote Count
3110,Mechenosets,5000000,63838,ru,0.414793,2006-12-10,3919731,0.0,5.6,7
3095,Missing,0,52623,en,0.229233,2007-01-01,1,0.0,4.3,2
3949,? ?¨??¥Ÿ¥?¥?¥Ÿ ???«?? ?¨¥???¥?«¥Ÿ?¯??¥¥?,0,197057,ru,0.402368,2003-04-12,234748,0.0,4.5,3
1396,Tutto tutto niente niente,5579750,161545,it,2.208906,2012-11-30,8927600,0.0,4.8,54
1370,The Worst Christmas of My Life,6843500,147868,it,3.800073,2012-12-22,10703234,0.0,5.5,86
...,...,...,...,...,...,...,...,...,...,...
2803,Jodhaa Akbar,8376800,14073,hi,12.237488,2008-02-15,13000000,213.0,7.6,74
3968,Gods and Generals,56000000,16072,en,5.374563,2003-02-21,12923936,214.0,6.1,49
4308,Lagaan: Once Upon a Time in India,5200000,19666,hi,4.974510,2001-06-15,8100000,224.0,7.2,125
1538,Gangs of Wasseypur,1400000,117691,hi,9.777219,2012-06-22,4100000,320.0,7.0,83
2165,Carlos,18000000,43434,en,4.558075,2010-05-19,871279,338.0,6.7,50

In [42]:
df.sorted = df.sort_values(by="Budget", ascending=False)
highest_budget_movie = df.sorted.head()
print(highest_budget_movie)

                                            Title     Budget      ID  \
1877  Pirates of the Caribbean: On Stranger Tides  380000000    1865
3007     Pirates of the Caribbean: At World's End  300000000     285
624                       Avengers: Age of Ultron  280000000   99861
3249                             Superman Returns  270000000    1452
30                  Transformers: The Last Knight  260000000  335988

     Original Language  Popularity Release Date     Revenue  Runtime  \
1877                en   27.887720   2011-05-14  1045713802    136.0
3007                en   31.363664   2007-05-19   961000000    169.0
624                 en   37.379420   2015-04-22  1405403694    141.0
3249                en   13.284712   2006-06-28   391081192    154.0
30                  en   39.186819   2017-06-21   604942143    149.0

      Vote Average  Vote Count
1877           6.4        5068
3007           6.9        4627
624            7.3        6908
3249           5.4        1429
30             6.2        1440